### ISSUE TITLE
elitetorrent fail

### ISSUE THREAD

**Issue by alfonsomiranda** [mgallego/Bach#1]
elitorrent spider fail when elitetorrent.net is down or returns an error.
Batch should make a number of attempts before failing, and when failure should continue with the next set.

**Comment by mgallego** [comment]
Desde el equipo de desarrollo de Bach te agradecemos tu propuesta y anotamos tu inquietud. Pero como eres Python Senior Developer Lead Of The Master Of The Universe lo picas tu y me haces un pull request. xD

Cuando saque un rato lo miro ;)

**Comment by mgallego** [comment]
Arreglado por @alfonsomiranda en PR #2
